---
title: "Summarizing Your Work for a General Audience"
linktitle: "3: Simplify"
date: "2020-12-20"
menu:
  year3:
    parent: "How to Write"
type: docs
weight: 3
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(error = TRUE, comment = NA, warnings = FALSE, errors = FALSE, messages = FALSE, tidy = FALSE, echo = FALSE)
```


You've written a complete paper - yay!! Now if only people would actually read it. We'll talk more about disseminating work in the **4th year** workshop, but for now, let's think about strategies to quickly and concisely summarize your work for a general audience. 

Here, we'll talk about some ways to assemble a quick message to convey your main findings.

<center>

```{r}
knitr::include_url("https://imccart.github.io/phd-workshop-content/year3/selling.html")
```


<p><a class="btn btn-primary btn-lg" target="_blank" href="https://imccart.github.io/phd-workshop-content/year3/selling.html"><i class="fas fa-external-link-alt"></i> View slides in new window</a></p>

</center>
