# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Etiquette"
  url = "etiquette"
  weight = 1

[[main]]
  name = "1st Year"
  url = "year1"
  weight = 2

[[main]]
  name = "2nd Year"
  url = "year2"
  weight = 3

[[main]]
  name = "3rd Year"
  url = "year3"
  weight = 4

[[main]]
  name = "4th Year"
  url = "year4"
  weight = 5

[[main]]
  name = "5th Year"
  url = "year5"
  weight = 6
  
[[main]]
  name = "Resources"
  url = "resource"
  weight = 7

[[etiquette]]
  name = "Overview"
  weight = 1

[[etiquette]]
  name = "Topics"
  weight = 2

[[year1]]
  name = "Overview"
  weight = 1

[[year1]]
  name = "Making it"
  weight = 2


[[year2]]
  name = "Overview"
  weight = 1

[[year2]]
  name = "What now?"
  weight = 2


[[year3]]
  name = "Overview"
  weight = 1

[[year3]]
  name = "Workflow"
  weight = 2

[[year3]]
  name = "How to Write"
  weight = 3

  
[[year4]]
  name = "Overview"
  weight = 1
  
[[year4]]
  name = "Will Anyone Read This?"
  weight = 2

[[year4]]
  name = "The Job Market"
  weight = 3
