---
title: "What's the point?"
date: "2020-12-20"
menu:
  year4:
    parent: Overview
type: docs
weight: -1
---

The main goal of the **4th year workshop** to help you sell yourself as best as possible on the job market. We'll do this in three steps:

### 1. Disseminating
What are the best ways to get your work out there? How do conferences work? Should you write that op-ed that someone told you to write? Can (and how should) you use social media? We'll offer some thoughts on all of these things. We'll also help you get a decent (and free!) website together to make sure your work is easily accessible to anyone interested.

### 2. Presenting
Presenting your work in different venues can be tricky. How do you best prepare for a "long-form" presentation like an invited talk or a smaller conference? What about a larger conference with shorter presentation times? What about when you run into someone in the elevator who asks what you're working on and you only have 30 seconds? We'll talk about how best to prepare for all of these different situations. We'll also talk about conference etiquette.

### 3. Preparing for the job market
Finally, let's go through our checklist to ensure you have all of the required elements of a well-prepared job market candidate. Does your CV look professional? Is your website fully functional with the right types of links? Have you decided where you'd like to apply and prepared your committee accordingly? If you're going on the academic market, have you prepared the non-research parts of your packet (a good syllabus and any other teaching material)?