---
title: "Resources"
page-layout: full
format: html
---

## Acknowledgements

I certainly didn't just sit down and write all of this stuff from scratch. All of this material benefited immensely from other resources. I'll try to list all of those resources here, although I'm sure I've missed something.

### Writing and Research

- Formulae for an [Introduction](https://www.albany.edu/spatial/training/5-The%20Introduction%20Formula.pdf) by Keith Head, [Body](https://marcfbellemare.com/wordpress/12797) by Marc Bellemare, and [Conclusion](https://marcfbellemare.com/wordpress/12060) by Marc Bellemare
- [Ten Most Important Rules of Writing Your Job Market Paper](http://home.bi.no/charlotte.ostergaard/students/tenruleswriting.pdf) by Claudia Goldin and Lawrence Katz
- [Paper writing gone Hollywood](https://science.sciencemag.org/content/355/6320/102)
- [Four steps to an applied micro paper](https://www.brown.edu/Research/Shapiro/pdfs/foursteps.pdf) by Jesse Shapiro
- [How to give an applied micro talk](https://www.brown.edu/Research/Shapiro/pdfs/applied_micro_slides.pdf) by Jesse Shapiro

### Presentations

- [Public speaking for academic economists](https://www.dropbox.com/s/vvzwjnjfa0yjqro/public_speaking_for_academic_economists.pdf?dl=0) by Rachel Meager
- [Beamer tips for presentations](https://github.com/paulgp/beamer-tips/blob/master/slides.pdf) by Paul Goldsmith-Pinkham

### Professional Development

- [The discussant's art](https://chrisblattman.com/2010/02/22/the-discussants-art/) by Chris Blattman
- Writing referee reports: [one](http://marcfbellemare.com/wordpress/5542) by Marc Bellemare, [another](https://blog.academicsequitur.com/2019/06/30/how-to-write-a-good-referee-report/) by Tatyana Deryugina, [another](https://are.berkeley.edu/courses/ARE251/2004/assignments/RRGuidelines.pdf) by Elisabeth Sadoulet, and [another](https://pubs.aeaweb.org/doi/pdf/10.1257/jep.31.1.231) by Berk, Harvey, and Hirshleifer in the JEP
- [How to be a great conference participant](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=1332144) by Art Carden

### Coding and Workflow

- [Stata coding guide](https://reifjulian.github.io/guide/) by Julian Reif
- [Code and data for the social sciences](https://www.brown.edu/Research/Shapiro/pdfs/CodeAndData.pdf) by Matthew Gentzkow and Jesse Shapiro
